### ISSUE TITLE
RetrofitManager.getInstance初始化有问题, 服务器的问题么? 

### ISSUE THREAD

**Issue by geekqian** [a371166028/likequanmintv#15]
`07-05 01:43:55.161 16026-16026/android.marshon.likequanmintv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: android.marshon.likequanmintv, PID: 16026
                                                                               java.lang.IllegalArgumentException: Illegal URL: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                                                                               <html xmlns="http://www.w3.org/1999/xhtml"><head>
                                                                               <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
                                                                               <title>系统发生错误</title>
                                                                               <style type="text/css">
                                                                               *{ padding: 0; margin: 0; }
                                                                               html{ overflow-y: scroll; }
                                                                               body{ background: #fff; font-family: '微软雅黑'; color: #333; font-size: 16px; }
                                                                               img{ border: 0; }
                                                                               .error{ padding: 24px 48px; }
                                                                               .face{ font-size: 100px; font-weight: normal; line-height: 120px; margin-bottom: 12px; }
                                                                               h1{ font-size: 32px; line-height: 48px; }
                                                                               .error .content{ padding-top: 10px}
                                                                               .error .info{ margin-bottom: 12px; }
                                                                               .error .info .title{ margin-bottom: 3px; }
                                                                               .error .info .title h3{ color: #000; font-weight: 700; font-size: 16px; }
                                                                               .error .info .text{ line-height: 24px; }
                                                                               .copyright{ padding: 12px 48px; color: #999; }
                                                                               .copyright a{ color: #000; text-decoration: none; }
                                                                               </style>
                                                                               </head>
                                                                               <body>
                                                                               <div class="error">
                                                                               <p class="face">:(</p>
                                                                               <h1>Call to a member function parseTemplate() on a non-object</h1>
                                                                               <div class="content">
                                                                               	<div class="info">
                                                                               		<div class="title">
                                                                               			<h3>错误位置</h3>
                                                                               		</div>
                                                                               		<div class="text">
                                                                               			<p>FILE: /var/www/html/dialogue/ThinkPHP/Library/Think/Controller.class.php &#12288;LINE: 166</p>
                                                                               		</div>
                                                                               	</div>
                                                                               </div>
                                                                               </div>
                                                                               <div class="copyright">
                                                                               <p><a title="官方网站" href="http://www.thinkphp.cn">ThinkPHP</a><sup>3.2.3</sup> { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]</p>
                                                                               </div>
                                                                               </body>
                                                                               </html>
                                                                               
                                                                                   at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:437)
                                                                                   at android.marshon.likequanmintv.librarys.http.RetrofitManager.<init>(RetrofitManager.java:98)
                                                                                   at android.marshon.likequanmintv.librarys.http.RetrofitManager.getInstance(RetrofitManager.java:177)
                                                                                   at android.marshon.likequanmintv.librarys.http.RetrofitManager.getInstance(RetrofitManager.java:172)
                                                                                   at android.marshon.likequanmintv.mvp.recommend.interactor.RecommendFragmentInteractorImpl.getStartInfo(RecommendFragmentInteractorImpl.java:41)
                                                                                   at android.marshon.likequanmintv.start.SplashActivity.initData(SplashActivity.java:68)
                                                                                   at android.marshon.likequanmintv.start.SplashActivity.access$100(SplashActivity.java:35)
                                                                                   at android.marshon.likequanmintv.start.SplashActivity$1.run(SplashActivity.java:56)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
`

**Comment by WilsonLee1992** [comment]
我也是这个问题呀

**Comment by WilsonLee1992** [comment]
baseUrl（）出问题了，服务器的原因么？
